# Generated by Django 3.2.24 on 2024-03-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='userId',
        ),
    ]
