# Generated by Django 3.2.24 on 2024-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acquired_by', models.CharField(max_length=255)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
